version: 0.2

phases:
#  pre_build:
#    commands:
#       - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 321019347814.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375
      - docker build -t 321019347814.dkr.ecr.ap-south-1.amazonaws.com/demo-output .
      - docker tag demo-output:latest 321019347814.dkr.ecr.ap-south-1.amazonaws.com/demo-output:latest
  post_build:
    commands:
      - docker push docker push 321019347814.dkr.ecr.ap-south-1.amazonaws.com/demo-output:latest
artifacts:
  files: build.json
